//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safety_Induction_V0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string User_Name { get; set; }
        public string Password { get; set; }
        public Nullable<short> InstID { get; set; }
        public Nullable<short> RoleID { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Role Role { get; set; }
    }
}
