//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safety_Induction_V0
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool_Box_Talk
    {
        public short ID { get; set; }
        public Nullable<short> TopicID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<short> InstID { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Topic Topic { get; set; }
    }
}
